version: 0.1
phases:
  build:
    commands:      
      - sam package --template-file template.yml --s3-bucket awscicd1 --output-template-file packaged-template.yaml
      - sam deploy --template-file packaged-template.yaml --stack-name my-date-time-app
artifacts:
  files:
    - packaged-template.yaml
