version: 0.1
phases:
  build:
    commands:      
        - sam build --template-file template.yaml
        - sam package --template-file template.yaml --s3-bucket awscicd1 --output-template-file packaged-template.yaml
#       - sam package --template-file template.yml --s3-bucket awscicd1 --output-template-file packaged-template.yaml
#       - sam deploy --template-file packaged-template.yaml --stack-name my-date-time-app --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
artifacts:
  files:
    - packaged-template.yaml
