version: 0.1
phases:
  build:
    commands:      
      - sam package --template-file template.yml --s3-bucket lambdasampleproject --output-template-file packaged-template.yaml
      - sam deploy --template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml
